# Cổng chạy ứng dụng trên Localhost
server.port=8080

# Cấu hình kết nối SQL Server (Tài khoản sa của Quỳnh)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OneShopDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate / JPA (Tự động tạo bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cấu hình gửi Mail OTP qua Gmail của Quỳnh
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2tuilaquynhne@gmail.com
spring.mail.password=nayquynhbunqua
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true